// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatformflu,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCgGMtOlgF_sSgmYOg0HMkkLWCavQJl0Q',
    appId: '1:859736008367:web:4889a9cd572eea2d84565a',
    messagingSenderId: '859736008367',
    projectId: 'sku-market-5910e',
    authDomain: 'sku-market-5910e.firebaseapp.com',
    storageBucket: 'sku-market-5910e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCClxMgOA1GgmcEbsedP7FyNUPMRy1ctGA',
    appId: '1:859736008367:android:115a7ff33ac90e6784565a',
    messagingSenderId: '859736008367',
    projectId: 'sku-market-5910e',
    storageBucket: 'sku-market-5910e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYE3GJvwz1Q7sYtt3x8JEvnMDrb3aJNk',
    appId: '1:859736008367:ios:e97da100c935072c84565a',
    messagingSenderId: '859736008367',
    projectId: 'sku-market-5910e',
    storageBucket: 'sku-market-5910e.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYE3GJvwz1Q7sYtt3x8JEvnMDrb3aJNk',
    appId: '1:859736008367:ios:e97da100c935072c84565a',
    messagingSenderId: '859736008367',
    projectId: 'sku-market-5910e',
    storageBucket: 'sku-market-5910e.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCgGMtOlgF_sSgmYOg0HMkkLWCavQJl0Q',
    appId: '1:859736008367:web:0b93a46d9a2ff69284565a',
    messagingSenderId: '859736008367',
    projectId: 'sku-market-5910e',
    authDomain: 'sku-market-5910e.firebaseapp.com',
    storageBucket: 'sku-market-5910e.appspot.com',
  );
}
